### ISSUE TITLE
Changing text in Mission section

### ISSUE THREAD

**Issue by aaron2382** [knownastheway/theway#13]
need to change outdated information under the Mission section for multiple projects

**Comment by aaron2382** [comment]
editing mispelling

**Comment by DanielBodnar** [comment]
Great job man!! Merged into master.

**Comment by aaron2382** [comment]
It is not merged into master, and not showing on the main page knownastheway.com

**Comment by DanielBodnar** [comment]
Created a new pull request and merged it into master.

**Comment by DanielBodnar** [comment]
@aaron2382 this should be merged and deployed - please check now.

**Comment by aaron2382** [comment]
Looks great. Thanks bud.... i see that when i speak your language shit get done  !!!!! hahaha

**Comment by aaron2382** [comment]
BTW, we gonna eed to BBQ again. those ribs were killer !

**Comment by DanielBodnar** [comment]
> Looks great. Thanks bud.... i see that when i speak your language shit get done !!!!! hahaha

Lauren wants to know why it took you so long to figure that out? ;-)

**Comment by DanielBodnar** [comment]
> BTW, we gonna need to BBQ again. those ribs were killer !

Thanks dude! Had I been a little more "with it" I would have sent you home with some leftovers. If you want smoked whatever before you leave, just let me know. I'll cover the wood, sides, and everything else if you're down for covering the cost of meat?
