### ISSUE TITLE
Grammar and Spelling Text Sections

### ISSUE THREAD

**Issue by aaron2382** [knownastheway/theway#18]
i've noticed a few grammar or spelling mistakes in the text section. I plan to fix them in beta and have you push it to master by the weekend.

**Comment by DanielBodnar** [comment]
@aaron2382 - go ahead and add details about what you'll be changing to this issue, so someone else can tackle it if they have time.

**Comment by aaron2382** [comment]
Can we merge development with master before 5pm Sat 27th, so page is ready for new people to visit site ?

**Comment by DanielBodnar** [comment]
Fix the commit and I'll merge it immediately

**Comment by DanielBodnar** [comment]
It seems like you made the changes in the wrong branch and did a merge request in the wrong direction. This can be easily fixed by just directly editing it in the development branch. I need you to do this because I don't know what you want it to say.

**Comment by aaron2382** [comment]
Ya, your gonna need to walk me through the steps again on another day.

I have made all edits in the development branch for this reason as to not screw it up.

All edits for text have been made now in development branch. Just merge it into the master when you get a chance, probably after the Bless slider is fixed and the Donate button redirect is also corrected.

**Comment by aaron2382** [comment]
Can we merge with the master before tomorrow ?

**Comment by aaron2382** [comment]
good to go
