### ISSUE TITLE
Bless Slider malfunctioning 

### ISSUE THREAD

**Issue by aaron2382** [knownastheway/theway#23]
When using the slider for the "Bless" section. The "organizational support" slide comes through multiple times, and not in order. 

Click though it twice and you will see the fault.

Can we correct it to only show once, as it is clicked though, until it comes back in, the correct order?

I do not have the skill to do this

**Comment by DanielBodnar** [comment]
Should be deploying now @aaron2382. You may close it after approving in production.

**Comment by DanielBodnar** [comment]
Deployed. Reopen issue if there's any problems, but it looks good to me.

**Comment by aaron2382** [comment]
Nice. You da man. Thanks a ton. . . see ya tomorrow
