### ISSUE TITLE
Paypal Donate Button Redirect

### ISSUE THREAD

**Issue by aaron2382** [knownastheway/theway#24]
1-We need to change the paypal donate button to redirect to the projects page bless.knownastheway.com

2-We also need the text above it to reflect this as well 
"To donate or set up recurring giving please click the button below and you'll be directed to PayPal's secure site"

Change "Paypal's secure site"  to say " our secure site "

**Comment by aaron2382** [comment]
Changed the text to reflect where the new redirect will take the customer.

Changed "paypal" to "Our"

**Comment by aaron2382** [comment]
Is it possible to update the redirect before tomorrow since many new people will be visiting the website ?

**Comment by DanielBodnar** [comment]
Should be deploying now. You may close it after approving in production.

**Comment by DanielBodnar** [comment]
Deployed. Reopen issue if there's any problems, but it looks good to me.
